# Generated by Django 4.0.3 on 2022-03-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
