# Generated by Django 3.1.7 on 2022-03-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_apps', '0003_auto_20220309_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='subscription',
        ),
        migrations.RenameModel(
            old_name='SubscriptionPlan',
            new_name='Plan',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_apps.userapp')),
                ('plan', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_apps.plan')),
            ],
        ),
    ]
