# Generated by Django 3.1.7 on 2022-03-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_apps', '0004_auto_20220309_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
