# Generated by Django 3.2.12 on 2022-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_apps', '0008_alter_userapp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
